version: '3'
services:
  loadbalancer:
    container_name: loadbalancer
    depends_on:
      - bucarestest1
      - bucarestest2
    image: "nginx:1.19.4-alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  bucarestest1:
    build:

    container_name: bucarestest1
    environment:
      SERVER_PORT: 8080
      SPRING_DATA_SOURCE_URL: jdbc:mysql://bucaresmysql:3306/bucares?serverTimezone=UTC&max_allowed_packet=15728640
      SPRING_DATA_SOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DIALECT: org.hibernate.dialect.MySQL8Dialect
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: superstrongpassword
      MYSQL_DATABASE: bucares
      INSTANCE: 1
    depends_on:
      - bucaresmysql
    image: "kristolopez/bucarestest:0.0.2-SNAPSHOT"
    ports:
      - 8080
  bucarestest2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bucarestest2
    environment:
      SERVER_PORT: 8081
      SPRING_DATA_SOURCE_URL: jdbc:mysql://bucaresmysql:3306/bucares?serverTimezone=UTC&max_allowed_packet=15728640
      SPRING_DATA_SOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DIALECT: org.hibernate.dialect.MySQL8Dialect
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: superstrongpassword
      MYSQL_DATABASE: bucares
      INSTANCE: 2
    depends_on:
      - bucaresmysql
    image: "kristolopez/bucarestest:0.0.2-SNAPSHOT"
    ports:
      - 8081
  bucaresmysql:
    container_name: bucaresmysql
    image: "mysql:8"
    environment:
      MYSQL_HOST: bucaresmysql
      MYSQL_DATABASE: bucares
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: superstrongpassword
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db:
