version: '3'
services:
  bucarestest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bucarestest
    environment:
      MYSQL_HOST: bucaresmysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: superstrongpassword
      MYSQL_DATABASE: bucares
      INSTANCE: 1
    depends_on:
      - bucaresmysql
    image: "kristolopez/bucarestest:0.0.2-SNAPSHOT"
    ports:
      - 8084:80
  bucaresmysql:
    container_name: bucaresmysql
    image: "mysql:8"
    environment:
      MYSQL_HOST: bucaresmysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bucares
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: superstrongpassword
    ports:
      - 9901:3306
    volumes:
    - "db:/var/lib/mysql"

volumes:
  db:
